version: '3.8'

services:
  backend:
    build: ./
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    networks:
      - app-network

  frontend:
    build: ./../Automacorp_frontend
    environment:
      - FRONTEND_PORT=${FRONTEND_PORT}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    networks:
      - app-network

networks:
  app-network:
